### ISSUE TITLE
Should show number of days until next funding period

### ISSUE THREAD

**Issue by JoeBostic** [JoeBostic/SpaceProgramFunding#5]
The display of the next funding period should not be just the raw date, but also show the number of days until the next funding period. This is a quality-of-life feature so the player doesn't have to do date-math.

**Comment by theonegalen** [comment]
Does the mod integrate with Kronometer in order to display / calculate the correct number of days for rescaled systems? That's a pretty important feature for me.

**Comment by JoeBostic** [comment]
Hmm. It looks to the Planetarium global object when determining duration of
each day. I presume that any mod that alters the main system would update
the Planetarium global object accordingly. I haven't testing this. The mod
DOES NOT use a hard-coded 6 hour day, so I have hope that it will work for
you.
